root: true
parser: '@typescript-eslint/parser'
parserOptions:
  tsconfigRootDir: ./
  project:
    - ./tsconfig.json
plugins:
  - '@typescript-eslint'
  - 'jest'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:jest/recommended'
  - 'prettier'
ignorePatterns:
  - 'src/.generated'
  - '*.md'
